# Generated by Django 2.1.2 on 2019-06-12 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.IntegerField(choices=[(0, 'Zone officer'), (1, 'State officer'), (2, 'District officer'), (3, 'Admin'), (4, 'Teacher'), (5, 'Student')])),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
    ]
